// This array combines products from all 5 product pages
const allProducts = [
     { name: "Scientific Calculator", price: 50, image: "https://via.placeholder.com/150" },
    { name: "Stapler", price: 120, image: "https://via.placeholder.com/150" },
    { name: "Notebook Set", price: 280, image: "https://via.placeholder.com/150" },
    { name: "Pen Pack", price: 80, image: "https://via.placeholder.com/150" },
    { name: "Clipboard", price: 320, image: "https://via.placeholder.com/150" },
    { name: "Markers", price: 150, image: "https://via.placeholder.com/150" },
    { name: "Scissors", price: 210, image: "https://via.placeholder.com/150" },
    { name: "Glue Stick", price: 90, image: "https://via.placeholder.com/150" },
    { name: "Highlighter", price: 60, image: "https://via.placeholder.com/150" },
    { name: "File Folder", price: 180, image: "https://via.placeholder.com/150" },
    { name: "Drawing Book", price: 240, image: "https://via.placeholder.com/150" },
    { name: "Staple Pins", price: 70, image: "https://via.placeholder.com/150" },

      { name: "Eraser Pack", price: 25, image: "https://via.placeholder.com/150" },
  { name: "Geometry Box", price: 180, image: "https://via.placeholder.com/150" },
  { name: "Pencil Set", price: 60, image: "https://via.placeholder.com/150" },
  { name: "Ruler 15cm", price: 20, image: "https://via.placeholder.com/150" },
  { name: "Sharpener", price: 18, image: "https://via.placeholder.com/150" },
  { name: "Water Bottle", price: 220, image: "https://via.placeholder.com/150" },
  { name: "School Bag", price: 450, image: "https://via.placeholder.com/150" },
  { name: "Lunch Box", price: 190, image: "https://via.placeholder.com/150" },
  { name: "Compass & Divider Set", price: 135, image: "https://via.placeholder.com/150" },
  { name: "Glue Stick", price: 70, image: "https://via.placeholder.com/150" },
  { name: "Crayons Pack", price: 99, image: "https://via.placeholder.com/150" },
  { name: "Color Pencils", price: 160, image: "https://via.placeholder.com/150" },

     { name: "Ball Pen", price: 20, image: "https://via.placeholder.com/150" },
    { name: "Gel Pen", price: 30, image: "https://via.placeholder.com/150" },
    { name: "Fountain Pen", price: 200, image: "https://via.placeholder.com/150" },
    { name: "Highlighter", price: 60, image: "https://via.placeholder.com/150" },
    { name: "Marker Set", price: 180, image: "https://via.placeholder.com/150" },
    { name: "Sketch Pen", price: 110, image: "https://via.placeholder.com/150" },
    { name: "Premium Pen", price: 450, image: "https://via.placeholder.com/150" },
    { name: "Refill Pack", price: 70, image: "https://via.placeholder.com/150" },
    { name: "Brush Pen", price: 140, image: "https://via.placeholder.com/150" },
    { name: "Signature Pen", price: 299, image: "https://via.placeholder.com/150" },
    { name: "Calligraphy Set", price: 350, image: "https://via.placeholder.com/150" },
    { name: "Pen Case", price: 95, image: "https://via.placeholder.com/150" },


    { name: "Spiral Notebook", price: 85, image: "https://via.placeholder.com/150" },
  { name: "Hardcover Diary", price: 150, image: "https://via.placeholder.com/150" },
  { name: "Drawing Book", price: 120, image: "https://via.placeholder.com/150" },
  { name: "A4 Ruled Sheets", price: 70, image: "https://via.placeholder.com/150" },
  { name: "Pocket Notebook", price: 45, image: "https://via.placeholder.com/150" },
  { name: "Sticky Notes Pack", price: 90, image: "https://via.placeholder.com/150" },
  { name: "Project Book", price: 110, image: "https://via.placeholder.com/150" },
  { name: "Sketch Pad", price: 180, image: "https://via.placeholder.com/150" },
  { name: "Note Pad", price: 60, image: "https://via.placeholder.com/150" },
  { name: "Blank Sheets Pack", price: 140, image: "https://via.placeholder.com/150" },
  { name: "Graph Paper Notebook", price: 130, image: "https://via.placeholder.com/150" },
  { name: "Perforated Sheets", price: 100, image: "https://via.placeholder.com/150" },


    { name: "A4 File Folder", price: 90, image: "https://via.placeholder.com/150" },
  { name: "Document File", price: 120, image: "https://via.placeholder.com/150" },
  { name: "Plastic Expanding Folder", price: 210, image: "https://via.placeholder.com/150" },
  { name: "Ring Binder", price: 160, image: "https://via.placeholder.com/150" },
  { name: "Report File", price: 60, image: "https://via.placeholder.com/150" },
  { name: "Cardboard File", price: 55, image: "https://via.placeholder.com/150" },
  { name: "Clip File", price: 130, image: "https://via.placeholder.com/150" },
  { name: "Zipper File Pouch", price: 110, image: "https://via.placeholder.com/150" },
  { name: "Paper Folder Set", price: 175, image: "https://via.placeholder.com/150" },
  { name: "Exam Pad File", price: 95, image: "https://via.placeholder.com/150" },
  { name: "Hard Cover Folder", price: 199, image: "https://via.placeholder.com/150" },
  { name: "Document Box File", price: 300, image: "https://via.placeholder.com/150" }
  // Add products from other 4 product card pages too
];
